### ISSUE TITLE
Can't log in to internet cafe pc after downgrade?

### ISSUE THREAD

**Issue by lucas-labs** [ClonkAndre/GTAIVDowngrader#1]
Hi, there! First of all, thanks for all your work!!
I'm having an issue after downgrading my 1.2.0.43 (Rockstar Launcher version, not steam) to 1.0.7. It seems I can't log into the internet cafe computers anymore (before downgrading it I was able to log in just fine), so I'm now stuck in one of Burcie's missions. I've been reading it might be related to downgrading and/or to zolikapatch. Have you ever heard of such a thing? 

I've tried removing ZolikaPatch, but when I do that I can't run the game from PlayGTAIV.exe (it says I don't have LaunchGTAIV.exe, and sure I don't have it. I only have GTAIV.exe in my GTA folder).

I've also moved the GTA install folder to another path after downgrading it, so that Rockstar couldnt find it and try to upgrade the game again (don't know if that's the right thing to do tho).

Any help would be really appreciated and thanks again for your great work!
Cheers.

**Comment by ClonkAndre** [comment]
If you still need help with this, please join my [Discord server](https://discord.gg/QtAgvkMeJ5) and ask in #help! Thanks!
