### ISSUE TITLE
Buggy UI in Wine (Linux)

### ISSUE THREAD

**Issue by LegitGreenBoi** [ClonkAndre/GTAIVDowngrader#4]
Obviously I know that Linux isn't officially supported, but this program does work and successfully downgrades using Wine but the only problem is that the UI is buggy and goes mostly blank when hovering/clicking buttons. It can kind of be worked around by maximizing and minimizing the window but it's spotty.

Not sure if there's any fix for this but it would be appreciated as this tool is really great :)

Here's a clip demonstrating the issue:
https://youtu.be/gAapGhXfJtA

**Comment by ClonkAndre** [comment]
Thanks for the report! Even tho Linux isn't officially supported, i will still try to somehow fix this bug. I sadly can't promise anything tho, cause the downgrader is built upon a Windows only framework.
Also thanks for the clip demonstrating the issue!

**Comment by LegitGreenBoi** [comment]
Great! Thanks for looking into this! Hopefully a fix can be worked out, this tool makes downgrading GTA IV so much quicker and pleasant and would be great to have the UI working smoothly through Wine :+1:

**Comment by ClonkAndre** [comment]
@LegitGreenBoi Hey, do you have discord? I'm currently working on a new update for the downgrader, and could really need the assistance from an actual Linux user 😀

**Comment by LegitGreenBoi** [comment]
@ClonkAndre Sure, message me on Discord: legitgreenboi

**Comment by ClonkAndre** [comment]
Should be fixed with version 2.0 of the downgrader.
