### ISSUE TITLE
FTP error 530 while trying to download e.g. 1070.zip

### ISSUE THREAD

**Issue by ThirdRealityStudios** [ClonkAndre/GTAIVDowngrader#9]
I figured out the downgrader does not want to download these version zip-files, e.g. 1070.zip.
I also figured out via Wireshark that the server simply rejects the connection trying to login with the ftp credentials.
The username seems to be accepted but after the Downgrader tries to use the password the FTP server does not want to give access?
Hence,
it is impossible to downgrade GTA IV currently.

**Comment by trivarialthea** [comment]
@ThirdRealityStudios Please read the forum. The ftp server is down. 

https://gtaforums.com/topic/976691-gta-iv-downgrader

![image](https://github.com/ClonkAndre/GTAIVDowngrader/assets/34968650/babcab53-7d73-48be-8ade-f499664c66fa)
